# Generated by Django 5.2 on 2026-03-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_experiment_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_format',
            field=models.CharField(default='markdown', help_text="'markdown' for legacy posts, 'html' for TipTap editor output.", max_length=16),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(help_text='Markdown or HTML from the editor'),
        ),
    ]
