# Generated by Django 5.2 on 2026-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hire_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'portfolio categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('meta', models.CharField(blank=True, help_text='Eyebrow label, e.g. Hardware · Prototype', max_length=120)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='portfolio/covers/')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.JSONField(blank=True, default=list, help_text='List of sections: [{"heading": str, "blocks": [...]}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='api.portfoliocategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
